image: maven:3.8.6-openjdk-21

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  script:
    - docker build -t your-docker-repo/your-app:latest .
    - docker push your-docker-repo/your-app:latest
  only:
    - main
